-- 002_create_conversations.sql
-- Conversation history across all sessions and all domains.
-- The broker writes every turn here. Used by the Context Assembler
-- to build the context packet prepended to every inference call.

CREATE TABLE IF NOT EXISTS conversations (
  id           bigserial      PRIMARY KEY,
  session_id   text           NOT NULL,      -- UUID per session, generated by broker on startup
  domain       text,                         -- which domain handled this turn (nullable = cross-domain)
  role         text           NOT NULL,      -- 'user' | 'assistant'
  content      text           NOT NULL,
  metadata     jsonb,                        -- job ticket, agent outputs, timing data, etc.
  created_at   timestamptz    NOT NULL DEFAULT NOW()
);

-- Fast recent-history lookup (Context Assembler reads last N turns by session)
CREATE INDEX IF NOT EXISTS conversations_session_idx
  ON conversations (session_id, created_at DESC);

-- Domain-scoped history (useful for per-agent history views in the UI)
CREATE INDEX IF NOT EXISTS conversations_domain_idx
  ON conversations (domain, created_at DESC);

COMMENT ON TABLE conversations IS
  'Full conversation history. Every user message and assistant response, timestamped.';
